# utils/gemini_helpers.py
"""Helpers for interacting with the Gemini API."""
import os
import json
from google import genai
from dotenv import load_dotenv

load_dotenv()
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

def generate_ideas_with_gemini(guidelines, num_ideas, user_input=None, existing_ideas=None):
    """Generates content ideas using the Gemini API (new google-genai SDK)."""
    if existing_ideas is None:
        existing_ideas = []

    if not GEMINI_API_KEY:
        raise ValueError("GEMINI_API_KEY must be set in the .env file.")

    client = genai.Client(api_key=GEMINI_API_KEY)
    prompt = f"""
    You are a creative social media manager for a tool rental company.
    Your task is to generate {num_ideas} fresh, engaging content ideas.
    Adhere strictly to the following Content Guidelines:
    ---
    {guidelines}
    ---
    """
    if user_input:
        prompt += f"Base your suggestions on this user-provided text:\n---\n{user_input}\n---\n"

    if existing_ideas:
        prompt += """
        IMPORTANT: Avoid generating ideas that are too similar to the following existing ideas. Focus on novelty and distinctiveness:
        ---
        """
        for i, idea in enumerate(existing_ideas):
            prompt += f"Idea {i+1}:\nTitle: {idea['title']}\nCopy: {idea['copy']}\n---\n"

    prompt += """
    For each idea, provide a content pillar, a short catchy title (under 100 chars), the full post body, and 3-5 relevant keywords for an image search.
    Return your response as a valid JSON array of objects. Each object must have "pillar", "title", "body", and "keywords" keys.
    Example:
    [
        {
            "pillar": "Tool Spotlight",
            "title": "Mini-Excavator: Small But Mighty",
            "body": "Check out this 15-second video on the versatility of our new mini-excavator. Perfect for tight spaces and big jobs! #ToolRental #Excavator",
            "keywords": "excavator, construction, digging, small space"
        }
    ]
    """
    print("Generating content ideas with Gemini...")
    try:
        response = client.models.generate_content(
            model="gemini-1.5-flash",
            contents=prompt
        )
        cleaned_response = response.candidates[0].content.parts[0].text.strip().replace("```json", "").replace("```", "").strip()
        return json.loads(cleaned_response)
    except Exception as e:
        print(f"Error generating ideas with Gemini: {e}")
        if 'response' in locals():
            print(f"Raw response from API: {getattr(response, 'text', '')}")
        return []

def generate_image_with_gemini(prompt, output_path):
    """Generates an image using Gemini (text-to-image) and saves it to output_path. Returns the local file path or None."""
    try:
        from google.genai import types
        from PIL import Image
        from io import BytesIO

        client = genai.Client(api_key=GEMINI_API_KEY)
        response = client.models.generate_content(
            model="gemini-2.0-flash-preview-image-generation",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_modalities=['TEXT', 'IMAGE']
            )
        )
        for part in response.candidates[0].content.parts:
            if hasattr(part, 'inline_data') and part.inline_data is not None:
                image = Image.open(BytesIO(part.inline_data.data))
                image.save(output_path)
                return output_path
        print("No image generated by Gemini.")
        return None
    except Exception as e:
        print(f"Error generating image with Gemini: {e}")
        return None
