
import os
import json
import logging
from datetime import datetime
from sanity import Client
from dotenv import load_dotenv
import uuid

load_dotenv(dotenv_path='/Users/tyler/Documents/rental_village/social_media/.env')

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Sanity client configuration
SANITY_PROJECT_ID = os.environ.get("SANITY_PROJECT_ID", "2pxuaj9k")
SANITY_DATASET = os.environ.get("SANITY_DATASET", "production")
SANITY_API_TOKEN = os.environ.get("SANITY_API_TOKEN") # Ensure this is set in your environment variables

sanity_client = Client(
    project_id=SANITY_PROJECT_ID,
    dataset=SANITY_DATASET,
    token=SANITY_API_TOKEN,
    use_cdn=False, # Use CDN for fresh data when writing
    logger=logger
)

def save_social_content_to_sanity(idea: dict) -> str | None:
    """
    Saves a generated social media content idea to Sanity.
    Returns the Sanity document ID if successful, None otherwise.
    """
    try:
        # Map the idea dictionary to the Sanity socialContent schema
        sanity_document = {
            "_type": "socialContent",
            "_id": str(uuid.uuid4()), # Generate a unique ID
            "title": idea.get("title"),
            "body": idea.get("body"),
            "platform": "", # Platform is not generated by Gemini, will be set later or in Notion
            "status": "generated", # Initial status after generation
            "performance_metrics": {},
            "related_equipment": [], # This would require more complex logic to link to equipment
            "ai_generation_metadata": {
                "model_used": "gemini-1.5-flash", # Assuming this is the model used
                "temperature": 0.7, # Assuming a default temperature
                "timestamp": datetime.now().isoformat(),
            },
        }

        # Add keywords if available, as a string for now, or convert to array if schema allows
        if "keywords" in idea and idea["keywords"]:
            sanity_document["ai_generation_metadata"]["keywords"] = idea["keywords"]

        # Use createOrReplace to handle potential re-runs or updates
        transactions = [{'createOrReplace': sanity_document}]
        result = sanity_client.mutate(transactions=transactions)
        logger.info(f"Sanity mutate result for social content: {json.dumps(result, indent=2)}")
        
        # Debugging: Print the full result structure
        logger.info(f"Full mutate result structure: {result}")

        if result and result.get('results') and result['results'][0].get('operation') in ['create', 'update']:
            doc_id = sanity_document['_id'] # Use the ID generated earlier
            logger.info(f"Successfully saved social content to Sanity with ID: {doc_id}")
            return doc_id
        else:
            logger.error(f"Failed to save social content to Sanity: Unexpected result structure or operation: {result}")
            return None

    except Exception as e:
        logger.error(f"Error saving social content to Sanity: {e}")
        return None
