# src/suggest_content.py
import os
import random
from datetime import date, timedelta
import notion_client
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# --- Configuration ---
NOTION_TOKEN = os.getenv("NOTION_TOKEN")
DATABASE_ID = os.getenv("DATABASE_ID")

# --- Placeholder Content Ideas ---
# In a real-world scenario, this could be generated by a call to a language model (e.g., Gemini)
# or be based on analyzing seasonal trends.
SUMMER_IDEAS = [
    {"pillar": "Project of the Week", "idea": "Build a new deck for summer BBQs. Rent our post-hole augers and saws!"},
    {"pillar": "Tool Spotlight", "idea": "Video Demo: The power and precision of our Kubota Mini Excavator."},
    {"pillar": "How-To Guide", "idea": "Blog Post: 5 Steps to a Perfectly Level Patio Base."},
    {"pillar": "Customer Feature", "idea": "Feature a local contractor's recent landscaping project."},
    {"pillar": "Safety First", "idea": "A quick guide to safely operating a pressure washer."},
]

def get_seasonal_ideas(num_ideas=3):
    """
    Selects a random subset of seasonal ideas.
    This is a placeholder for a more advanced idea generation engine.
    """
    return random.sample(SUMMER_IDEAS, min(num_ideas, len(SUMMER_IDEAS)))

def add_idea_to_notion(notion, idea_content):
    """
    Adds a single content idea to the Notion database.
    """
    # Calculate a suggested post date for 1-2 weeks in the future
    suggested_date = (date.today() + timedelta(days=random.randint(7, 14))).isoformat()

    try:
        notion.pages.create(
            parent={"database_id": DATABASE_ID},
            properties={
                "Name": {
                    "title": [
                        {
                            "text": {
                                "content": f"[{idea_content['pillar']}] {idea_content['idea'][:100]}"
                            }
                        }
                    ]
                },
                "Status": {
                    "select": {
                        "name": "AI Suggestion"
                    }
                },
                "Content Pillar": {
                    "select": {
                        "name": "Project of the Week"
                    }
                },
                "Post Date": {
                    "date": {
                        "start": suggested_date
                    }
                },
                # This is where the full idea would go, perhaps in the body of the page.
                # For this draft, we'll keep it simple.
            }
        )
        print(f"Successfully added idea: {idea_content['idea']}")
    except Exception as e:
        print(f"Error adding idea to Notion: {e}")

def main():
    """
    Main function to generate ideas and push them to Notion.
    """
    if not NOTION_TOKEN or not DATABASE_ID:
        raise ValueError("NOTION_TOKEN and DATABASE_ID must be set in the .env file.")

    notion = notion_client.Client(auth=NOTION_TOKEN)
    ideas_to_generate = get_seasonal_ideas(3) # Generate 3 new ideas

    print("Starting to add new content ideas to Notion...")
    for idea in ideas_to_generate:
        add_idea_to_notion(notion, idea)
    print("Finished adding ideas.")

if __name__ == "__main__":
    main()
