# src/suggest_content.py
import os
import argparse
import json
import random
from datetime import date, timedelta
import notion_client
import requests
from google import genai
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# --- Configuration ---
NOTION_API_KEY = os.getenv("NOTION_API_KEY")
NOTION_DATABASE_ID = os.getenv("NOTION_DATABASE_ID")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

# --- Helper Functions ---

def read_file_content(file_path):
    """Reads the content of a specified file."""
    try:
        with open(file_path, 'r') as f:
            return f.read()
    except FileNotFoundError:
        print(f"Error: The file {file_path} was not found.")
        return None

def generate_ideas_with_gemini(guidelines, num_ideas, user_input=None):
    """Generates content ideas using the Gemini API (new google-genai SDK)."""
    if not GEMINI_API_KEY:
        raise ValueError("GEMINI_API_KEY must be set in the .env file.")

    client = genai.Client(api_key=GEMINI_API_KEY)
    prompt = f"""
    You are a creative social media manager for a tool rental company.
    Your task is to generate {num_ideas} fresh, engaging content ideas.
    Adhere strictly to the following Content Guidelines:
    ---
    {guidelines}
    ---
    """
    if user_input:
        prompt += f"Base your suggestions on this user-provided text:\n---\n{user_input}\n---\n"

    prompt += """
    For each idea, provide a content pillar, a short catchy title (under 100 chars), the full post body, and 3-5 relevant keywords for an image search.
    Return your response as a valid JSON array of objects. Each object must have "pillar", "title", "body", and "keywords" keys.
    Example:
    [
        {
            "pillar": "Tool Spotlight",
            "title": "Mini-Excavator: Small But Mighty",
            "body": "Check out this 15-second video on the versatility of our new mini-excavator. Perfect for tight spaces and big jobs! #ToolRental #Excavator",
            "keywords": "excavator, construction, digging, small space"
        }
    ]
    """
    print("Generating content ideas with Gemini...")
    try:
        response = client.models.generate_content(
            model="gemini-1.5-flash",
            contents=prompt
        )
        cleaned_response = response.candidates[0].content.parts[0].text.strip().replace("```json", "").replace("```", "").strip()
        return json.loads(cleaned_response)
    except Exception as e:
        print(f"Error generating ideas with Gemini: {e}")
        if 'response' in locals():
            print(f"Raw response from API: {getattr(response, 'text', '')}")
        return []

def generate_image_with_gemini(prompt, output_path):
    """Generates an image using Gemini (text-to-image) and saves it to output_path. Returns the local file path or None."""
    try:
        from google.genai import types
        from PIL import Image
        from io import BytesIO

        client = genai.Client(api_key=GEMINI_API_KEY)
        response = client.models.generate_content(
            model="gemini-2.0-flash-preview-image-generation",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_modalities=['TEXT', 'IMAGE']
            )
        )
        for part in response.candidates[0].content.parts:
            if hasattr(part, 'inline_data') and part.inline_data is not None:
                image = Image.open(BytesIO(part.inline_data.data))
                image.save(output_path)
                return output_path
        print("No image generated by Gemini.")
        return None
    except Exception as e:
        print(f"Error generating image with Gemini: {e}")
        return None

def upload_image_to_notion(notion, page_id, image_path):
    """Uploads an image file to the Notion page's 'Creative' (files) property using Notion's direct upload."""
    try:
        # Step 1: Get a presigned URL from Notion for the upload
        get_url_endpoint = f"https://api.notion.com/v1/pages/{page_id}/properties/Creative/files"
        headers = {
            "Authorization": f"Bearer {notion.auth}",
            "Notion-Version": "2022-06-28",
            "Content-Type": "application/json"
        }
        file_info = {
            "name": os.path.basename(image_path),
            "type": "image/png" # Assuming PNG, adjust if necessary
        }
        
        print("--- Requesting Notion upload URL ---")
        response = requests.post(get_url_endpoint, headers=headers, json={"files": [file_info]})
        response.raise_for_status()
        upload_data = response.json()
        
        presigned_url = upload_data['files'][0]['uploadUrl']
        notion_file_url = upload_data['files'][0]['url'] # This is the URL Notion will use internally
        
        # Step 2: Upload the actual file to the presigned URL
        print(f"--- Uploading image to {presigned_url} ---")
        with open(image_path, 'rb') as f:
            upload_response = requests.put(
                presigned_url, 
                data=f,
                headers={"Content-Type": "image/png"}
            )
            upload_response.raise_for_status()
        
        print("Image uploaded successfully to Notion's internal storage.")

        # Step 3: Update the Notion page with the internal Notion file URL
        notion.pages.update(
            page_id=page_id,
            properties={
                "Creative": {
                    "files": [
                        {"type": "file", "name": os.path.basename(image_path), "file": {"url": notion_file_url}}
                    ]
                }
            }
        )
        print(f"Updated Notion Creative field with internal URL: {notion_file_url}")
    except requests.exceptions.RequestException as e:
        print(f"Error uploading image to Notion: {e}")
        if e.response:
            print(f"Response content: {e.response.text}")
    except Exception as e:
        print(f"An unexpected error occurred during Notion image upload: {e}")

def add_idea_to_notion(notion, idea):
    """Adds a single content idea, with AI-generated image, to the Notion database."""
    suggested_date = (date.today() + timedelta(days=random.randint(7, 14))).isoformat()
    properties = {
        "Name": {"title": [{"text": {"content": idea['title']}}]},
        "Status": {"status": {"name": "AI Suggestion"}},
        "Content Pillar": {"select": {"name": idea['pillar']}},
        "Post Date": {"date": {"start": suggested_date}},
        "Copy": {"rich_text": [{"type": "text", "text": {"content": idea['body']}}]}
    }
    try:
        # Create the page first
        page_response = notion.pages.create(parent={"database_id": NOTION_DATABASE_ID}, properties=properties)
        page_id = page_response['id']
        print(f"Successfully added idea: {idea['title']}")
        # Generate image prompt from keywords or body
        image_prompt = idea.get('body') or idea.get('keywords', '')
        image_filename = f"{idea['title'].replace(' ', '_').replace('/', '_')}.png"
        script_dir = os.path.dirname(__file__)
        images_dir = os.path.join(script_dir, '..', 'generated_images')
        os.makedirs(images_dir, exist_ok=True)
        output_path = os.path.join(images_dir, image_filename)
        local_image_path = generate_image_with_gemini(image_prompt, output_path)
        if local_image_path:
            print(f"Generated image for '{idea['title']}' and saved to '{local_image_path}'.")
            upload_image_to_notion(notion, page_id, local_image_path)
    except Exception as e:
        print(f"Error adding idea to Notion: {e}")

def main():
    parser = argparse.ArgumentParser(description="Generate social media content ideas and add them to Notion.")
    parser.add_argument("--num-ideas", type=int, default=3, help="Number of content ideas to generate.")
    parser.add_argument("--input-text", type=str, help="Pasted text to use as inspiration for idea generation.")
    args = parser.parse_args()

    if not all([NOTION_API_KEY, NOTION_DATABASE_ID, GEMINI_API_KEY]):
        raise ValueError("Required API keys (NOTION, GEMINI) must be set in the .env file.")

    script_dir = os.path.dirname(__file__)
    guidelines_path = os.path.join(script_dir, '..', 'strategy_documents', 'content_guidelines.md')
    content_guidelines = read_file_content(guidelines_path)
    if not content_guidelines:
        return

    notion = notion_client.Client(auth=NOTION_API_KEY)
    ideas = generate_ideas_with_gemini(content_guidelines, args.num_ideas, args.input_text)

    if not ideas:
        print("No ideas were generated. Exiting.")
        return

    print("\nStarting to add new content ideas to Notion...")
    for idea in ideas:
        add_idea_to_notion(notion, idea)
    print("Finished adding ideas.")

if __name__ == "__main__":
    main()